from ..tool import Tool

class ThinkTool(Tool):
    def __init__(self):
        super().__init__()

        self.name = "Think"
        self.description = (
            "Internal reasoning step. "
            "Use to plan before acting."
        )

        self.is_safe = True

        self.arguments = {
            "type": "object",
            "properties": {
                "thought": {
                    "type": "string"
                }
            },
            "required": ["thought"]
        }

    def execute(self, args):
        return args["thought"]
    
class PlanTool(Tool):
    def __init__(self):
        super().__init__()

        self.name = "Plan"
        self.description = (
            "Create and manage task plans."
        )

        self.is_safe = True

        self.plan = []

        self.arguments = {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "create",
                        "complete",
                        "get"
                    ]
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "index": {
                    "type": "integer"
                }
            },
            "required": ["action"]
        }

    def execute(self, args):
        action = args["action"]

        if action == "create":
            self.plan = [
                {
                    "task": step,
                    "completed": False
                }
                for step in args.get("steps", [])
            ]

            return {
                "status": "created",
                "plan": self.plan
            }

        if action == "complete":
            index = args["index"]

            if index < 0 or index >= len(self.plan):
                return {
                    "error": "Invalid step index"
                }

            self.plan[index]["completed"] = True

            return {
                "status": "completed",
                "step": self.plan[index]
            }

        if action == "get":
            return {
                "plan": self.plan
            }

        return {
            "error": f"Unknown action: {action}"
        }
    
class QuestionTool(Tool):
    def __init__(self):
        super().__init__()

        self.name = "Question"
        self.description = (
            "Ask the human for additional information "
            "when the agent is uncertain. "
            "Provide suggested answers, but allow a custom response."
        )

        self.is_safe = True

        self.arguments = {
            "type": "object",
            "properties": {
                "question": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "suggestions": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": (
                        "Suggested answers generated by the model. "
                        "The user may select one or provide a custom answer."
                    )
                }
            },
            "required": ["question"]
        }

    def execute(self, args):
        return {
            "waiting_for_user": True,
            "question": args["question"],
            "context": args.get("context", ""),
            "suggestions": args.get("suggestions", []),
            "allow_custom_answer": True
        }